# 工作流名称
name: test deploy

# 触发条件：push 到 main 分支时运行
on:
  push:
    branches: [ main ]

# 任务
jobs:
  pnpm-build:
    # 运行环境：GitHub免费的Ubuntu服务器
    runs-on: ubuntu-latest

    # 具体步骤
    steps:
      # 允许访问package.json
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm build
