# 工作流名称
name: test deploy

# 触发条件：push 到 main 分支时运行
on:
  push:
    branches: [ main ]

permissions:
  contents: write

# 任务
jobs:
  npm-build:
    name: npm-build work
    # 运行环境：GitHub免费的Ubuntu服务器
    runs-on: ubuntu-latest

    # 具体步骤
    steps:
      # 允许访问package.json
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖和项目打包
        run: 
          npm install
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 部署到gh-pages分支
          folder: out